Added new command that will return the days until an event (events based off an object of events with date formats)
TimmyRB/SDNEBot pull request #8
Opened 2020-11-01 00:02 UTC by N3rdP1um23

2020-11-01 06:51 UTC, TimmyRB commented on lib/handlers/messages.ts
> +	if(m.startsWith('!daysUntil')) {
Add `return` statement to command when successfully executed to stop Bot from showing ❓ Reaction

2020-11-01 06:56 UTC, TimmyRB requested changes

2020-11-01 06:56 UTC, TimmyRB commented on lib/funcs.ts
> +    tips.push({ 'name': 'Get days until an event (mainly holiday)', 'value': '```!daysUntil event name```'})
Move this beside where the other Tips are set that also do not require special permissions to have this appear before Admin Commands

2020-11-01 06:56 UTC, TimmyRB commented on lib/handlers/messages.ts
> +	if(m.startsWith('!daysUntil')) {
Add `return` statement to command when successfully executed to stop Bot from showing ❓ Reaction

2020-11-02 02:45 UTC, N3rdP1um23 commented on lib/funcs.ts
> +    tips.push({ 'name': 'Get days until an event (mainly holiday)', 'value': '```!daysUntil event name```'})
Done!

2020-11-02 02:45 UTC, N3rdP1um23 commented on lib/handlers/messages.ts
> +	if(m.startsWith('!daysUntil')) {
Done!

2020-11-04 04:16 UTC, TimmyRB approved these changes

2020-11-04 04:16 UTC, merged